---
- name: Install apache
  apt: name=apache2 state=present

- name: Remove default config
  file: path=/etc/apache2/sites-enabled/default state=absent
  notify:
        - restart apache
                        
