---
- name: Installing additional modules
  apt: name=python-pymysql state=present

- name: Create wordpress database
  mysql_db: name=wordpress state=present encoding=utf8

- name: Create wordpress user
  mysql_user: name=wordpressuser password=password priv=wordpress.*:ALL host='localhost' state=present

- name: Download and extract wordpress
  unarchive: src=http://wordpress.org/latest.tar.gz dest=/tmp/ remote_src=yes
  register: htac

- name: Create htaccess
  file: path=/tmp/wordpress/.htaccess state=touch mode=0660
  when: htac.changed
       
- name: Get random salts for WP config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  become: no
  become_method: sudo
  when: htac.changed 

- name: Template wp config
  template: src=wp-config.php.j2 dest=/tmp/wordpress/wp-config.php
  register: wp_config
  when: wp_salt.changed

- name : Wordpress deployment
  shell: cp -a /tmp/wordpress/. /var/www/site1/
  when: wp_config.changed

- name: Change ownership of site directory
  file: path=/var/www/site1/ owner=www-site1 group=www-site1 state=directory recurse=yes
  when: site1.changed

