---
- name: Create directory for site
  file: path=/var/www/site1 state=directory
  register: site1
       
- name: Create directory for logs
  file: path=/var/www/log state=directory

- name: Create directory for apache logs
  file: path=/var/www/log/apache2 state=directory

- name: Create directory for nginx logs
  file: path=/var/www/log/nginx state=directory

- name: Create directory for mysql logs
  file: path=/var/www/log/mysql state=directory

- name: creater group for 1st site
  group: name=www-site1

- name: Create user for 1st site
  user: name=www-site1 group=www-site1 home=/var/www/site1/

- name: Change ownership of site directory
  file: path=/var/www/site1/ owner=www-site1 group=www-site1 state=directory recurse=yes
  when: site1.changed

