---
- name: Download and extract phpmyadmin
  unarchive: src=https://files.phpmyadmin.net/phpMyAdmin/4.8.3/phpMyAdmin-4.8.3-all-languages.zip dest=/tmp/ remote_src=yes
  register: "phpmya"

- name: Create directory for PMY
  file: path=/var/www/site1/phpmyadmin state=directory mode=0755

- name: Copy phpmyadmin in site1 directory
  shell: cp -a /tmp/phpMyAdmin-4.8.3-all-languages/. /var/www/site1/phpmyadmin/
  when: phpmya.changed

- name: Template phpmyadmin congf
  template: src=phpmyadmin.conf.j2 dest=/var/www/site1/config.inc.php mode=0750
  notify: restart apache

- name: Change ownership of site directory
  file: path=/var/www/site1/ owner=www-site1 group=www-site1 state=directory recurse=yes
  when: site1.changed

